import type { Metadata } from 'next';
import './globals.css';
import { GeistSans } from 'geist/font/sans';
import { Inter as FontSans } from 'next/font/google';
import { ThemeProvider } from '@/src/providers/theme-provider';
import { Toaster } from '@/src/components/ui/toaster';
import { UserContextProvider } from '@/src/context/UserContext';
import { AppContextProvider } from '@/src/context/AppContext';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

// Define global metadata
const metadata: Metadata = {
	title: {
		default: 'JNext',
		template: '%s | JNext', // Use a template for dynamic titles
	},
	description: 'Generated by create next app',
	icons: {
		icon: 'icon.svg', // Global favicon
	},
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
	return (
		<html lang="en">
			<body className={GeistSans.className}>
				<AppContextProvider>
					<UserContextProvider>
						<ThemeProvider attribute="class" defaultTheme="system" enableSystem>
							{children}
							<Toaster />
						</ThemeProvider>
					</UserContextProvider>
				</AppContextProvider>
			</body>
		</html>
	);
};

export default RootLayout;
export { metadata };
